# fly.toml app configuration file generated for ehr-team2-app on 2023-06-26T16:09:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ehr-team2-app"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "local"
  APP_DEBUG="true"
  DB_CONNECTION="pgsql"
  DB_HOST="db.flvffliindwmiaqbneuk.supabase.co"
  DB_PORT="5432"
  DB_DATABASE="postgres"
  DB_USERNAME="postgres"
  DB_PASSWORD="ehr-team2-database"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  VONAGE_API_KEY="e0f71074"
  VONAGE_API_SECRET="lCF5qIFwcS4C4sXx"
  BRAND_NAME="+639476371070"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
